apiVersion : apps/v1
kind: Deployment
metadata:
  name: pinkaks 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pinkaks
  template:
    metadata:
      labels:
        app: pinkaks 
    spec:
      containers:
        - name: pinkaks 
          image: acrhackfestjim11437.azurecr.io/pinkaks
          ports:
          - containerPort: 80
